apiVersion: storage.aceplatform.org/v1alpha1
kind: XStorageAccount
metadata:
  name: myapp-storage
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  # annotations:
  #   argocd.argoproj.io/managed-by: crossplane   
spec:
  parameters:
    storageAccountName: myappsa2024
    resourceGroupName: myapp-rg
    location: eastus
    sku: Standard_LRS