apiVersion: storage.aceplatform.org/v1alpha1
kind: XStorageAccount
metadata:
  name: backstgtstraghav
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parameters:
    storageAccountName: backstgtstraghav
    resourceGroupName: myapp-rg
    location: eastus
    sku: Standard_LRS