apiVersion: v1
kind: Secret
metadata:
  name: platform-repository-github-ssh-placeholder
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: platform-repo
  type: git
  url: git@github.com:placeholder/placeholder.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----