apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name : xstorageaccounts.storage.aceplatform.org
spec:
  scope: Namespaced
  group: storage.aceplatform.org
  names:
    kind: XStorageAccount
    plural: xstorageaccounts
  defaultCompositionRef:
    name: azure-storage-account
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
              spec:
                type: object
                required:
                  - parameters
                properties:
                  parameters:
                    type: object
                    required:
                      - storageAccountName
                      - resourceGroupName
                      - location
                    properties:
                      storageAccountName:
                        type: string
                        description: Name of the Azure Storage Account
                        maxLength: 24
                        minLength: 3
                        pattern: '^[a-z0-9]+$'
                      resourceGroupName:
                        type: string
                        description: Azure Resource Group to deploy into
                      location:
                        type: string
                        description: Azure region
                        enum:
                          - eastus
                          - westus
                          - westeurope
                          - uksouth
                      sku:
                        type: string
                        description: Storage account SKU
                        default: Standard_LRS
                        enum:
                          - Standard_LRS
                          - Standard_GRS
                          - Premium_LRS                      


