apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xstorageaccounts.platform.example.org
spec:
  group: platform.example.org
  names:
    kind: XStorageAccount
    plural: xstorageaccounts
  claimNames:
    kind: StorageAccount
    plural: storageaccounts
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [parameters]
              properties:
                parameters:
                  type: object
                  required: [resourceGroupName, location, accountTier, accountReplicationType]
                  properties:
                    resourceGroupName:
                      type: string
                    location:
                      type: string
                    accountTier:
                      type: string
                      enum: ["Standard", "Premium"]
                    accountReplicationType:
                      type: string
                      enum: ["LRS", "GRS", "RAGRS", "ZRS", "GZRS", "RAGZRS"]