apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/rbharadwaj16/platform-infra.git
    targetRevision: HEAD
    path: platform-core/backstage/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true