apiVersion: compute.aceplatform.org/v1alpha1
kind: XAKSCluster
metadata:
  name: raghavbstest
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parameters:
    clusterName: raghavbstest
    resourceGroupName: myapp-rg
    location: eastus
    localAccountDisabled: false
    defaultNodePool:
      name: system
      vmSize: Standard_DC2as_v5
      nodeCount: 1
      enableAutoScaling: false
