apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-translator-service-secret.yaml
  - 02-translator-service-deployment.yaml
  - 03-translator-service-svc.yaml
  - 04-translator-service-argo-app.yaml
