apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - 01-crossplane-ns.yaml
 - 02-crossplane-argo-app.yaml
 - 03-crossplane-provider-functions.yaml
 - xrd/xrd-storageaccount.yaml
 - compositions/composition-storageaccount.yaml
 #- xr/xr-sa.yaml
